### ISSUE TITLE
404 Page Links are Wrong

### ISSUE THREAD

**Issue by vkoves** [emberjs/guides#1560]
I was stumbling around trying to see if there was a newer version of an old Ember Cookbook article, and ended up on the 404 page. It turns out the 404 page links to the Ember guides using [this link](https://guides.emberjs.com/guides) which also yields a 404 page, yielding a 404 loop.

Super tiny issue, but just wanted to pointed it out.

**Comment by acorncom** [comment]
@vkoves Ouch, sorry to hear it.  Could you send over a link to the specific page where you found the broken link?  And hopefully a screenshot too?  That'd help us track things down quicker ;-)

**Comment by locks** [comment]
This has been addressed in https://github.com/emberjs/guides/pull/1422. Did we muck up the deploy?

**Comment by etherelly** [comment]
Choosing a different version from this page returns a 404: https://guides.emberjs.com/v1.13.0/understanding-ember/dependency-injection-and-service-lookup/ and the 404 loop is still there. Cheers!

**Comment by jsArgus** [comment]
Yep 404 loop still exists as described above. Screenshot: 
![404_loop](https://cloud.githubusercontent.com/assets/573477/18328685/2e7d016e-7550-11e6-9b0c-eafac72d88bf.png)

**Comment by locks** [comment]
Fixed, appreciated!
