### ISSUE TITLE
404 page's image doesn't load

### ISSUE THREAD

**Issue by sivakumar-kailasam** [emberjs/guides#1883]
On reaching https://guides.emberjs.com/v2.12.0/models/working-with-relationships/ you'd notice that http://emberjs.com/images/tomsters/fishy.png is missing.

**Comment by travismchan** [comment]
Both links seem to be broken.

**Comment by toddjordan** [comment]
probably has to do with the change a few weeks back that adds fingerprints to each of the public tomster images.  The guides will likely likely need to have the image locally instead of referring to the one at emberjs.com

**Comment by RyanNerd** [comment]
See PR #1919 that I created. This should fix the fishy.png link.  Not sure what is meant by 

> both links appear to be broken

**Comment by RyanNerd** [comment]
**Note**: I am not able to test my changes. Due to running the guides via middleman I am unable to trigger the 404.html page to load. 

http://localhost:4567/404.html  gives me a file not found error.

**Comment by acorncom** [comment]
Sadly the change we made here fixes things in this repo, but doesn't fix our 404 page, which is referenced in this file here: https://github.com/emberjs/guides.emberjs.com/blob/master/snapshots/404.html#L67

We'll need to update that file to get this resolved ...
