### ISSUE TITLE
Naming Conventions Table CSS exceeds 100% width

### ISSUE THREAD

**Issue by ashleygwilliams** [emberjs/guides#399]
on http://guides.emberjs.com/v1.12.0/concepts/naming-conventions/
table exceeds 100% width, overflow is cut off, cannot read template column

<img width="814" alt="screen shot 2015-07-05 at 5 44 43 pm" src="https://cloud.githubusercontent.com/assets/1163554/8513531/cd01c2f4-233d-11e5-89fb-ad8fce5ff829.png">

in Chrome 43.0.2357.130 (64-bit)

**Comment by pmasucci** [comment]
So I would love to fix this bug, but I'm wondering if someone can point me in the right direction as far as best practices go (I'm about as junior as you can get). The problem can be solved by wrapping the table in a div with overflow:scroll. Is it okay to add that right into naming-conventions.md and then add a .scroll class in the css?

Everything in the .md files that I've looked through so far seems to be purely html with no classes so I didn't want to mix those up if it isn't okay.

**Comment by eccegordo** [comment]
Just say no to scroll overflow. :smile: 

How about a tree view to represent the convention?

<table>
    <tr>
        <th>Route Name</th>
        <th>Convention</th>

    </tr>
    <tr>
        <td><code>posts</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── post.js  
 ├── routes/
 │   └── post.js  
 └── templates/
     └── posts.hbs
            </pre>
        </td>
    </tr>

    <tr>
        <td><code>posts.favorites</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── posts/  
 │      └── favorites.js  
 ├── routes/
 │   └── posts/
 │      └── favorites.js  
 └── templates/
     └── posts/
        └── favorites.hbs
          </pre>
        </td>
    </tr>

    <tr>
        <td><code>posts.post</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── posts/  
 │      └── post.js  
 ├── routes/
 │   └── posts/
 │      └── post.js  
 └── templates/
     └── posts/
        └── post.hbs
            </pre>
        </td>
    </tr>
</table>

Here is the markup

```

<table>
    <tr>
        <th>Route Name</th>
        <th>Convention</th>

    </tr>
    <tr>
        <td><code>posts</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── post.js  
 ├── routes/
 │   └── post.js  
 └── templates/
     └── posts.hbs
            </pre>
        </td>
    </tr>

    <tr>
        <td><code>posts.favorites</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── posts/  
 │      └── favorites.js  
 ├── routes/
 │   └── posts/
 │      └── favorites.js  
 └── templates/
     └── posts/
        └── favorites.hbs
          </pre>
        </td>
    </tr>

    <tr>
        <td><code>posts.post</code></td>
        <td>
            <pre>
app
 ├── controllers/
 │   └── posts/  
 │      └── post.js  
 ├── routes/
 │   └── posts/
 │      └── post.js  
 └── templates/
     └── posts/
        └── post.hbs
            </pre>
        </td>
    </tr>
</table>
```

**Comment by michaelrkn** [comment]
That looks great to me! Can you open a PR?

**Comment by eccegordo** [comment]
Sure I can do that. I am a little unclear about the guides branching. Do I need to submit distinct PRs against each version where this code might live.

I will give it a try let me know if aligning the PRs correctly.

**Comment by michaelrkn** [comment]
Past versions of the guides are static and immutable. You can just submit a PR and the change will be included in the next version of the guides. Thank you!

**Comment by eccegordo** [comment]
OK got it so just PR against master then. Thanks! Coming right up.

**Comment by rwjblue** [comment]
Fixed by #399.

**Comment by eccegordo** [comment]
This doesn't look like it was merged into the 1.13 guides. I still see the truncated HTML table.

Also, fix should be back ported to older guides.

**Comment by michaelrkn** [comment]
@eccegordo: See the README: "No attempt is made to update content, layout, or styles for older versions of the Guides. They are considered static and immutable." This fix, and all others, won't be backported. It would just be a nightmare trying to maintain so many different versions of the Guides.

The 1.13 release was cut from before this fix was added. We will be re-cutting the 1.13 release early this coming week, and this fix will be in it.

Thanks for contributing!
