### ISSUE TITLE
Version selection menu should be orthogonal

### ISSUE THREAD

**Issue by humanchimp** [emberjs/guides#496]
It would be great if changing the version of the docs using the menu did not navigate me back to the main page of the docs. Instead, it should take me to the page corresponding to the current page, but for the version of the docs I have selected from the menu.

<img width="335" alt="screenshot 2015-07-29 17 06 54" src="https://cloud.githubusercontent.com/assets/575266/8972968/54c5d426-3614-11e5-924d-6034efe7acd3.png">

**Comment by locks** [comment]
It's working for me between `v1.13.0` and `v1.12.0`.

**Comment by rwjblue** [comment]
This should be fixed in the most recent version of the guides.

**Comment by trek** [comment]
> it should take me to the page corresponding to the current page, but for the version of the docs I have selected from the menu.

This still not always work as there is no guarantee a version of the guide you're looking at exists in previous or future revisions (relative to where you are looking)

**Comment by humanchimp** [comment]
@trek that the corresponding page must actually exist in the documentation is quite obvious. You can't link to something that's not there. I get it.

This is still broken on v1.11 which I'm needing to use for unfortunate reasons. I'll edit the URL instead of using the menu.

**Comment by humanchimp** [comment]
It's my opinion that fixing this only in the most recent versions doesn't actually resolve this issue, since the feature in question is designed to navigate between the different versions.

**Comment by locks** [comment]
@humanchimp https://github.com/emberjs/guides/blob/master/README.md#contributing

**Comment by humanchimp** [comment]
@locks I assume you are pointing me to this sentence:
> Please note that no attempt is made to update content, layout, or styles for older versions of the Guides. They are considered static and immutable, as it is too difficult to maintain content for every version ever released. Issues will only be fixed for future releases.

Normally, I understand why such a position would be taken, but since this feature is specifically designed to navigate between the versions, not fixing the older versions breaks the entire feature. But I digress. I'll just train myself to edit the URL by hand instead of trying to use the broken feature.

**Comment by locks** [comment]
If you can figure out a way to send us a PR that we can cherry pick into the branches, I'll bring up the issue in the meetings, but I have my hands full at the moment with other parts of the guides and can't investigate.
